/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniIndexRouteImport } from './routes/uni/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as PersonalIndexRouteImport } from './routes/personal/index'
import { Route as UniRocketRouteImport } from './routes/uni/rocket'
import { Route as UniQuadcopterRouteImport } from './routes/uni/quadcopter'
import { Route as UniGliderRouteImport } from './routes/uni/glider'
import { Route as TeamSolotronRouteImport } from './routes/team/solotron'
import { Route as TeamIforgeRouteImport } from './routes/team/iforge'
import { Route as PersonalPidRouteImport } from './routes/personal/pid'
import { Route as PersonalOscilloscopeRouteImport } from './routes/personal/oscilloscope'
import { Route as PersonalEscRouteImport } from './routes/personal/esc'
import { Route as PersonalDevboardRouteImport } from './routes/personal/devboard'
import { Route as HomeExperiencesRouteImport } from './routes/home/experiences'
import { Route as HomeEducationRouteImport } from './routes/home/education'
import { Route as HomeAboutRouteImport } from './routes/home/about'
import { Route as TeamSeadreamIndexRouteImport } from './routes/team/seadream/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniIndexRoute = UniIndexRouteImport.update({
  id: '/uni/',
  path: '/uni/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalIndexRoute = PersonalIndexRouteImport.update({
  id: '/personal/',
  path: '/personal/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniRocketRoute = UniRocketRouteImport.update({
  id: '/uni/rocket',
  path: '/uni/rocket',
  getParentRoute: () => rootRouteImport,
} as any)
const UniQuadcopterRoute = UniQuadcopterRouteImport.update({
  id: '/uni/quadcopter',
  path: '/uni/quadcopter',
  getParentRoute: () => rootRouteImport,
} as any)
const UniGliderRoute = UniGliderRouteImport.update({
  id: '/uni/glider',
  path: '/uni/glider',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSolotronRoute = TeamSolotronRouteImport.update({
  id: '/team/solotron',
  path: '/team/solotron',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIforgeRoute = TeamIforgeRouteImport.update({
  id: '/team/iforge',
  path: '/team/iforge',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalPidRoute = PersonalPidRouteImport.update({
  id: '/personal/pid',
  path: '/personal/pid',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalOscilloscopeRoute = PersonalOscilloscopeRouteImport.update({
  id: '/personal/oscilloscope',
  path: '/personal/oscilloscope',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalEscRoute = PersonalEscRouteImport.update({
  id: '/personal/esc',
  path: '/personal/esc',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDevboardRoute = PersonalDevboardRouteImport.update({
  id: '/personal/devboard',
  path: '/personal/devboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeExperiencesRoute = HomeExperiencesRouteImport.update({
  id: '/home/experiences',
  path: '/home/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeEducationRoute = HomeEducationRouteImport.update({
  id: '/home/education',
  path: '/home/education',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/home/about',
  path: '/home/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSeadreamIndexRoute = TeamSeadreamIndexRouteImport.update({
  id: '/team/seadream/',
  path: '/team/seadream/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/about': typeof HomeAboutRoute
  '/home/education': typeof HomeEducationRoute
  '/home/experiences': typeof HomeExperiencesRoute
  '/personal/devboard': typeof PersonalDevboardRoute
  '/personal/esc': typeof PersonalEscRoute
  '/personal/oscilloscope': typeof PersonalOscilloscopeRoute
  '/personal/pid': typeof PersonalPidRoute
  '/team/iforge': typeof TeamIforgeRoute
  '/team/solotron': typeof TeamSolotronRoute
  '/uni/glider': typeof UniGliderRoute
  '/uni/quadcopter': typeof UniQuadcopterRoute
  '/uni/rocket': typeof UniRocketRoute
  '/personal/': typeof PersonalIndexRoute
  '/team/': typeof TeamIndexRoute
  '/uni/': typeof UniIndexRoute
  '/team/seadream/': typeof TeamSeadreamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/about': typeof HomeAboutRoute
  '/home/education': typeof HomeEducationRoute
  '/home/experiences': typeof HomeExperiencesRoute
  '/personal/devboard': typeof PersonalDevboardRoute
  '/personal/esc': typeof PersonalEscRoute
  '/personal/oscilloscope': typeof PersonalOscilloscopeRoute
  '/personal/pid': typeof PersonalPidRoute
  '/team/iforge': typeof TeamIforgeRoute
  '/team/solotron': typeof TeamSolotronRoute
  '/uni/glider': typeof UniGliderRoute
  '/uni/quadcopter': typeof UniQuadcopterRoute
  '/uni/rocket': typeof UniRocketRoute
  '/personal': typeof PersonalIndexRoute
  '/team': typeof TeamIndexRoute
  '/uni': typeof UniIndexRoute
  '/team/seadream': typeof TeamSeadreamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home/about': typeof HomeAboutRoute
  '/home/education': typeof HomeEducationRoute
  '/home/experiences': typeof HomeExperiencesRoute
  '/personal/devboard': typeof PersonalDevboardRoute
  '/personal/esc': typeof PersonalEscRoute
  '/personal/oscilloscope': typeof PersonalOscilloscopeRoute
  '/personal/pid': typeof PersonalPidRoute
  '/team/iforge': typeof TeamIforgeRoute
  '/team/solotron': typeof TeamSolotronRoute
  '/uni/glider': typeof UniGliderRoute
  '/uni/quadcopter': typeof UniQuadcopterRoute
  '/uni/rocket': typeof UniRocketRoute
  '/personal/': typeof PersonalIndexRoute
  '/team/': typeof TeamIndexRoute
  '/uni/': typeof UniIndexRoute
  '/team/seadream/': typeof TeamSeadreamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/about'
    | '/home/education'
    | '/home/experiences'
    | '/personal/devboard'
    | '/personal/esc'
    | '/personal/oscilloscope'
    | '/personal/pid'
    | '/team/iforge'
    | '/team/solotron'
    | '/uni/glider'
    | '/uni/quadcopter'
    | '/uni/rocket'
    | '/personal/'
    | '/team/'
    | '/uni/'
    | '/team/seadream/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/about'
    | '/home/education'
    | '/home/experiences'
    | '/personal/devboard'
    | '/personal/esc'
    | '/personal/oscilloscope'
    | '/personal/pid'
    | '/team/iforge'
    | '/team/solotron'
    | '/uni/glider'
    | '/uni/quadcopter'
    | '/uni/rocket'
    | '/personal'
    | '/team'
    | '/uni'
    | '/team/seadream'
  id:
    | '__root__'
    | '/'
    | '/home/about'
    | '/home/education'
    | '/home/experiences'
    | '/personal/devboard'
    | '/personal/esc'
    | '/personal/oscilloscope'
    | '/personal/pid'
    | '/team/iforge'
    | '/team/solotron'
    | '/uni/glider'
    | '/uni/quadcopter'
    | '/uni/rocket'
    | '/personal/'
    | '/team/'
    | '/uni/'
    | '/team/seadream/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeAboutRoute: typeof HomeAboutRoute
  HomeEducationRoute: typeof HomeEducationRoute
  HomeExperiencesRoute: typeof HomeExperiencesRoute
  PersonalDevboardRoute: typeof PersonalDevboardRoute
  PersonalEscRoute: typeof PersonalEscRoute
  PersonalOscilloscopeRoute: typeof PersonalOscilloscopeRoute
  PersonalPidRoute: typeof PersonalPidRoute
  TeamIforgeRoute: typeof TeamIforgeRoute
  TeamSolotronRoute: typeof TeamSolotronRoute
  UniGliderRoute: typeof UniGliderRoute
  UniQuadcopterRoute: typeof UniQuadcopterRoute
  UniRocketRoute: typeof UniRocketRoute
  PersonalIndexRoute: typeof PersonalIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  UniIndexRoute: typeof UniIndexRoute
  TeamSeadreamIndexRoute: typeof TeamSeadreamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni/': {
      id: '/uni/'
      path: '/uni'
      fullPath: '/uni/'
      preLoaderRoute: typeof UniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/': {
      id: '/personal/'
      path: '/personal'
      fullPath: '/personal/'
      preLoaderRoute: typeof PersonalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni/rocket': {
      id: '/uni/rocket'
      path: '/uni/rocket'
      fullPath: '/uni/rocket'
      preLoaderRoute: typeof UniRocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni/quadcopter': {
      id: '/uni/quadcopter'
      path: '/uni/quadcopter'
      fullPath: '/uni/quadcopter'
      preLoaderRoute: typeof UniQuadcopterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni/glider': {
      id: '/uni/glider'
      path: '/uni/glider'
      fullPath: '/uni/glider'
      preLoaderRoute: typeof UniGliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/solotron': {
      id: '/team/solotron'
      path: '/team/solotron'
      fullPath: '/team/solotron'
      preLoaderRoute: typeof TeamSolotronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/iforge': {
      id: '/team/iforge'
      path: '/team/iforge'
      fullPath: '/team/iforge'
      preLoaderRoute: typeof TeamIforgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/pid': {
      id: '/personal/pid'
      path: '/personal/pid'
      fullPath: '/personal/pid'
      preLoaderRoute: typeof PersonalPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/oscilloscope': {
      id: '/personal/oscilloscope'
      path: '/personal/oscilloscope'
      fullPath: '/personal/oscilloscope'
      preLoaderRoute: typeof PersonalOscilloscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/esc': {
      id: '/personal/esc'
      path: '/personal/esc'
      fullPath: '/personal/esc'
      preLoaderRoute: typeof PersonalEscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/devboard': {
      id: '/personal/devboard'
      path: '/personal/devboard'
      fullPath: '/personal/devboard'
      preLoaderRoute: typeof PersonalDevboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/experiences': {
      id: '/home/experiences'
      path: '/home/experiences'
      fullPath: '/home/experiences'
      preLoaderRoute: typeof HomeExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/education': {
      id: '/home/education'
      path: '/home/education'
      fullPath: '/home/education'
      preLoaderRoute: typeof HomeEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/about': {
      id: '/home/about'
      path: '/home/about'
      fullPath: '/home/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/seadream/': {
      id: '/team/seadream/'
      path: '/team/seadream'
      fullPath: '/team/seadream/'
      preLoaderRoute: typeof TeamSeadreamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeAboutRoute: HomeAboutRoute,
  HomeEducationRoute: HomeEducationRoute,
  HomeExperiencesRoute: HomeExperiencesRoute,
  PersonalDevboardRoute: PersonalDevboardRoute,
  PersonalEscRoute: PersonalEscRoute,
  PersonalOscilloscopeRoute: PersonalOscilloscopeRoute,
  PersonalPidRoute: PersonalPidRoute,
  TeamIforgeRoute: TeamIforgeRoute,
  TeamSolotronRoute: TeamSolotronRoute,
  UniGliderRoute: UniGliderRoute,
  UniQuadcopterRoute: UniQuadcopterRoute,
  UniRocketRoute: UniRocketRoute,
  PersonalIndexRoute: PersonalIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  UniIndexRoute: UniIndexRoute,
  TeamSeadreamIndexRoute: TeamSeadreamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
